In [5]:
import torch 
from torch.autograd import Variable
x = torch.Tensor(3,4)
print('x Tensor',x)

y = torch.zeros(3,4)
print('y Tensor',y)
z = torch.randn(3,4)
print('z Tensor',z)


ivar = Variable(z)

print('Valiable ivar',ivar)

print ("ivar.data: ",ivar.data, ",ivar.grad: ",ivar.grad)



x Tensor tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
y Tensor tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
z Tensor tensor([[-0.1885, -0.8433, -0.6395,  0.7881],
        [ 1.0639, -0.9542, -0.0163, -0.6947],
        [ 1.6679,  0.2680, -1.1372, -0.2167]])
Valiable ivar tensor([[-0.1885, -0.8433, -0.6395,  0.7881],
        [ 1.0639, -0.9542, -0.0163, -0.6947],
        [ 1.6679,  0.2680, -1.1372, -0.2167]])
ivar.data:  tensor([[-0.1885, -0.8433, -0.6395,  0.7881],
        [ 1.0639, -0.9542, -0.0163, -0.6947],
        [ 1.6679,  0.2680, -1.1372, -0.2167]]) ,ivar.grad:  None


In [33]:
import torch
from torch.autograd import Variable
x = Variable(torch.ones(2,2),requires_grad=True)

print(x)

y = x+2

print(y)


z= y*y*3

out = z.mean()
print(z,out)

out.backward()
print(f'x 的导数为： {x.grad}')

# weight = weight + learning_rate * gradient

# learning_rate = 0.01

# for f in model.parameters():
#     f.data.sub_(f.grad.data * learning_rate)
    

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)
x 的导数为： tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [52]:

import torch 
from torch.autograd import Variable
import torch.nn as nn 
import torch.nn.functional as F 
# 损失函数的代码示例说明
sample = Variable(torch.ones(2,2))
a = torch.Tensor([[0,1],[2,3]])
target = Variable(a)

# nn.L1loss  loss(x,y)=1/N ∑|x-y|

criterion = nn.L1Loss()
loss = criterion(sample,target)
print(f'L1loss的损失是:{loss}')


# nn.SmoothL1Loss  误差在（-1,1）上是平方损失，其他情况为L1损失 

criterion1 = nn.SmoothL1Loss()

# 根据公式计算，的出来是 5/8 = 0.625 
loss1 = criterion1(sample,target)


print(f'SmoothL1Loss的损失是:{loss1}')


# nn.MSELoss 平方损失函数，计算公式是预测值和真实值之间的平方和的平均数

criterion2 = nn.MSELoss()

# 根据公式计算，=1/4(|1-0|^2+|1-1|^2+|1-2|^2+|1-3|^2)=3/2=1.5
loss2 = criterion2(sample,target)


print(f'MSELoss的损失是:{loss2}')

# nn.BCELoss 二分类的交叉熵，

criterion3 = nn.BCELoss()

# 根据公式计算，
loss3 = criterion3(sample,target)


print(f'BCELoss的损失是:{loss3}')

# nn.CrossEntropyLoss() 交叉熵损失函数 一般用于图像识别模型

criterion4 = nn.CrossEntropyLoss()

loss4 = criterion4(sample,target)

print(f'CrossEntropyLoss的损失是：{loss4}')

# nn.NLLoss  负对数似然损失函数 ，一般用于图像识别模型

loss5 = F.nll_loss(torch.Tensor([1.0]),torch.Tensor([2.0]))

print(f'NLLoss的损失是：{loss5}')



L1loss的损失是:1.0
SmoothL1Loss的损失是:0.625
MSELoss的损失是:1.5
BCELoss的损失是:-50.0
CrossEntropyLoss的损失是：2.079441547393799


RuntimeError: expected scalar type Long but found Float

In [54]:
import torch 

x_data = [1.0,2.0,3.0]
y_data = [2.0,4.0,6.0]

# 默认不带有梯度
w = torch.Tensor([1.0])
w.requires_grad = True

def forward(x):
    return x*w # 返回值含有梯度 ，此处乘法运算符被重载，可用于Tensor计算

# 定义一个损失函数
def loss(x,y): 
    y_pred = forward(x)
    return (y_pred-y) **2

# 此处的item 是Tensor 中的 grad 计算的转换的一个标量
print('Predict (before training)',4,forward(4).item())

# 梯度下降的次数
for epoch in range(100):
    # 均进行遍历
    for x,y in zip(x_data,y_data):
        # 前向传播：前向反馈的过程是建立计算图的过程
        l = loss(x,y)
        # 反向传播：求出来所有需要的梯度，反向传播之后的计算图就被释放
        l.backward()
        # 输出梯度
        print('\t grad:',x,y,w.grad.item())
        # 构建时用Tensor,权重更新时用.data 
        w.data -= 0.01 * w.grad.data
        # 引入Pytorch 中的grad 自动球每个样本时的梯度
        print(f'w.grad.item() : {w.grad.item()}')
        print(f'w.grad.data :{w.grad.data}')
        
        # 将本轮计算的grad 清零，否则默认是dl/dw 累加到下一轮
        w.grad.data.zero_()
    print(f'process:{epoch},{l.item()}')
    
print('Predict (after training)',4,forward(4).item())


Predict (before training) 4 4.0
	 grad: 1.0 2.0 -2.0
w.grad.item() : -2.0
w.grad.data :tensor([-2.])
	 grad: 2.0 4.0 -7.840000152587891
w.grad.item() : -7.840000152587891
w.grad.data :tensor([-7.8400])
	 grad: 3.0 6.0 -16.228801727294922
w.grad.item() : -16.228801727294922
w.grad.data :tensor([-16.2288])
process:0,7.315943717956543
	 grad: 1.0 2.0 -1.478623867034912
w.grad.item() : -1.478623867034912
w.grad.data :tensor([-1.4786])
	 grad: 2.0 4.0 -5.796205520629883
w.grad.item() : -5.796205520629883
w.grad.data :tensor([-5.7962])
	 grad: 3.0 6.0 -11.998146057128906
w.grad.item() : -11.998146057128906
w.grad.data :tensor([-11.9981])
process:1,3.9987640380859375
	 grad: 1.0 2.0 -1.0931644439697266
w.grad.item() : -1.0931644439697266
w.grad.data :tensor([-1.0932])
	 grad: 2.0 4.0 -4.285204887390137
w.grad.item() : -4.285204887390137
w.grad.data :tensor([-4.2852])
	 grad: 3.0 6.0 -8.870372772216797
w.grad.item() : -8.870372772216797
w.grad.data :tensor([-8.8704])
process:2,2.18565320968627